python ./hw2.py hw2flatlight.txt
python ./hw2.py hw2gouraudlight.txt
python ./hw2.py hw2lookatortho.txt
python ./hw2.py hw2pointlightg.txt
python ./hw2.py hw2pointlightpf.txt
python ./hw2.py hw2pointlightpg.txt
python ./hw2.py hw2rectbezf.txt
python ./hw2.py hw2rectbezg.txt
python ./hw2.py hw2rectbezglit.txt
python ./hw2.py hw2tribezf.txt
python ./hw2.py hw2tribezg.txt
python ./hw2.py hw2tribezglit.txt
python ./hw2.py hw2tripf.txt
python ./hw2.py hw2tripg.txt
python ./hw2.py hw2triptf.txt
python ./hw2.py hw2triptg.txt
python ./hw2.py hw2trif.txt
python ./hw2.py hw2color.txt
python ./hw2.py hw2depth.txt
python ./hw2.py hw2culling.txt
python ./hw2.py hw2lookat.txt
python ./hw2.py hw2translate.txt
python ./hw2.py hw2scalec.txt
python ./hw2.py hw2scale.txt
python ./hw2.py hw2bigtris.txt
python ./hw2.py hw2rotatex.txt
python ./hw2.py hw2loadmv.txt
python ./hw2.py hw2multmv.txt
python ./hw2.py hw2ortho.txt
python ./hw2.py hw2clipplane.txt
python ./hw2.py hw2frustum.txt
python ./hw2.py hw2pixelclip.txt
python ./hw2.py hw2rotate.txt
python ./hw2.py hw2rotatec.txt